### Obteniendo info
GET http://localhost:5554/api

### Obtener todos los usuarios
GET http://localhost:5554/api/users



### Obtener usuario por email
GET http://localhost:5554/api/users/mendoza.e@gmail.com

### Crear un nuevo usuario
POST http://localhost:5554/api/users/register
Content-Type: application/json

{
    "username": "Ailenpaez",
    "email": "paez.a@gmail.com",
    "password": "contra345",
    "phone": 151345411
}

### Login 
POST http://localhost:5554/api/users/login
Content-Type: application/json


{
    "username": "elianamendoza",
    "password": "Meneli"
}

### Borrar usuario
DELETE http://localhost:5554/api/users/melinaarias
Content-Type: application/json

### Actualizar datos usuario 
PATCH http://localhost:5554/api/users/ElianaMendoza

{
    "username": "pepito"
}

### Logout
DELETE http://localhost:5554/api/users/logout
Content-Type: application/json
Authorization: b2c281e4-5c55-4ec4-89e7-4547ff34606f

{
    "username": "ElianaMendoza"
}

### Obtener todas las bicis 
GET http://localhost:5554/api/bikes/

### Crear nueva bici
POST http://localhost:5554/api/bikes/
Content-Type: application/json

{
    "type": "Mountain",
    "model": "Nordic MTB X 1.0",
    "colour": [
                "negro",
                "blanco",
                "verde"
            ],
    "priceHour": 566,
    "quantity": 3
}

### Borrar bicicleta
DELETE http://localhost:5554/api/bikes/1be994da-6059-4565-8897-9934f17adb89

### Actualizar datos
PATCH http://localhost:5554/api/bikes/e87ea8c9-8833-4e6f-b6d2-7563fee31567
Content-Type: application/json

{
    "priceHour": 900
}

### Buscar bicicleta por id 
GET http://localhost:5554/api/bikes/g90ea8c9-8833-4e6f-b6d2-7563fee32696